version: '3.3'

services:
  ollama_chat_app:
    build: .
    container_name: ollama-chat-app
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - .:/usr/src/app
    restart: unless-stopped


